### ISSUE TITLE
Procedure ?

### ISSUE THREAD

**Issue by vk4tux** [g4klx/DV4RX#1]
Please advise? Attempt's to use this with port 13920, 13921, 42000 all failed with or without dv_serial running & MMDVM on and off.

Thankyou

**Comment by vk4tux** [comment]
[root@fedora23desk YSFRX] # ./YSFRX 42000 450000000
E: 2016-05-25 03:01:55.193 Cannot open device - 42000
[root@fedora23desk YSFRX] # ./YSFRX 13920 450000000
E: 2016-05-25 03:02:12.928 Cannot open device - 13920
[root@fedora23desk YSFRX] # ./YSFRX 13921 450000000
E: 2016-05-25 03:02:18.880 Cannot open device - 13921

**Comment by g4klx** [comment]
The port is the serial port of the DV4mini attached to your computer. It doesn't talk to any network, it's purely a data dumping tool.
